Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "server-dba"
    config.vm.box_check_update = false
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end