Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "server-front"
    config.vm.box_check_update = false
    config.vm.network "forwarded_port", guest: 80, host: 8083
    config.vm.network "private_network", ip: "192.168.56.12"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end